### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by orenbenkiki** [scverse/Muon.jl#29]
I have just released alpha versions of https://github.com/tanaylab/DataAxesFormats.jl and https://pypi.org/project/dafpy/ - R wrappers are WIP.

This takes a different approach to overcoming the limitations of `AnnData`. I use `Muon` to import/export `AnnData` objects to interoperate with current computational pipelines.

I'm forced to use the head revision as a dependency since the last published version doesn't support some features. Would it be possible to have an official release "soon"? The last one is from half a year ago.

**Comment by ilia-kats** [comment]
I've just released 0.2.1.

**Comment by orenbenkiki** [comment]
Thanks!
